//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagerAppDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AppDTEntities : DbContext
    {
        public AppDTEntities()
            : base("name=AppDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PRODUCTOS_PV> PRODUCTOS_PV { get; set; }
        public DbSet<SUBLINEAS_PV> SUBLINEAS_PV { get; set; }
        public DbSet<USUARIOS_PV> USUARIOS_PV { get; set; }
        public DbSet<VENTASTICKET_PV> VENTASTICKET_PV { get; set; }
        public DbSet<LINEAS_PV> LINEAS_PV { get; set; }
        public DbSet<TICKETS_PV> TICKETS_PV { get; set; }
    
        public virtual ObjectResult<Nullable<double>> ps_VentasTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("ps_VentasTotal");
        }
    
        public virtual ObjectResult<ps_TicketsTotal_Result> ps_TicketsTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ps_TicketsTotal_Result>("ps_TicketsTotal");
        }
    }
}
