//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagerAppDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBLINEAS_PV
    {
        public int Subl_Id { get; set; }
        public string Subl_Name { get; set; }
        public int Line_Id { get; set; }
    }
}
