//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagerAppDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS_PV
    {
        public int User_Id { get; set; }
        public string User_nombre { get; set; }
        public string User_Login { get; set; }
        public string User_Password { get; set; }
        public string User_Tipo { get; set; }
        public string Empl_Id { get; set; }
    }
}
