//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagerAppDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTASTICKET_PV
    {
        public int Venta_Id { get; set; }
        public int Ticket_Id { get; set; }
        public int Prod_Id { get; set; }
        public decimal Venta_Cantidad { get; set; }
        public decimal Prod_Price { get; set; }
        public decimal Venta_Importe { get; set; }
    }
}
